#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("sas.Resource", IsApplication=true)]

namespace sas
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::sas.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::sas.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blue_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001a
			public const int Heading = 2131165210;
			
			// aapt resource value: 0x7f070030
			public const int Image = 2131165232;
			
			// aapt resource value: 0x7f07001b
			public const int List = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int List2 = 2131165212;
			
			// aapt resource value: 0x7f070028
			public const int Text = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int Text1 = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int Text2 = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int Text3 = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int Text4 = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int Text5 = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int Text6 = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int Text7 = 2131165231;
			
			// aapt resource value: 0x7f070026
			public const int android_lstServicios = 2131165222;
			
			// aapt resource value: 0x7f070017
			public const int btnBuscar = 2131165207;
			
			// aapt resource value: 0x7f070027
			public const int btnCerrarSesion = 2131165223;
			
			// aapt resource value: 0x7f07000a
			public const int btnIngresar = 2131165194;
			
			// aapt resource value: 0x7f070024
			public const int btnIniciarServicio = 2131165220;
			
			// aapt resource value: 0x7f070018
			public const int btnRegistrarResultado = 2131165208;
			
			// aapt resource value: 0x7f070010
			public const int btnRegistroInicial = 2131165200;
			
			// aapt resource value: 0x7f070019
			public const int btnRegistroLocal = 2131165209;
			
			// aapt resource value: 0x7f070013
			public const int btnTranslado = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int btnVolverBase = 2131165202;
			
			// aapt resource value: 0x7f070000
			public const int lblBuscar = 2131165184;
			
			// aapt resource value: 0x7f070016
			public const int lblDescrpcionDestinoDesenlace = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int lblDestinoDesenlace = 2131165204;
			
			// aapt resource value: 0x7f070002
			public const int lstSasDatos = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int mProgress = 2131165187;
			
			// aapt resource value: 0x7f070033
			public const int menu_share = 2131165235;
			
			// aapt resource value: 0x7f07000f
			public const int tableLayout1 = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int tableLayout2 = 2131165201;
			
			// aapt resource value: 0x7f070004
			public const int textView3 = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int textView4 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int textView5 = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int textView6 = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int textView7 = 2131165197;
			
			// aapt resource value: 0x7f07001f
			public const int textView8 = 2131165215;
			
			// aapt resource value: 0x7f070021
			public const int textView9 = 2131165217;
			
			// aapt resource value: 0x7f070032
			public const int toolbar = 2131165234;
			
			// aapt resource value: 0x7f070031
			public const int toolbar1 = 2131165233;
			
			// aapt resource value: 0x7f070001
			public const int txtBusqueda = 2131165185;
			
			// aapt resource value: 0x7f070008
			public const int txtClave = 2131165192;
			
			// aapt resource value: 0x7f070015
			public const int txtDestinoDesenlace = 2131165205;
			
			// aapt resource value: 0x7f070022
			public const int txtDireccion1 = 2131165218;
			
			// aapt resource value: 0x7f07000e
			public const int txtEdad = 2131165198;
			
			// aapt resource value: 0x7f07001d
			public const int txtHoraLlamada = 2131165213;
			
			// aapt resource value: 0x7f070023
			public const int txtMotivo1 = 2131165219;
			
			// aapt resource value: 0x7f07000c
			public const int txtNombrePaciente = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int txtNroSolicitud = 2131165195;
			
			// aapt resource value: 0x7f070020
			public const int txtSolicitante = 2131165216;
			
			// aapt resource value: 0x7f07001e
			public const int txtTipo = 2131165214;
			
			// aapt resource value: 0x7f070025
			public const int txtTitulo = 2131165221;
			
			// aapt resource value: 0x7f070005
			public const int txtUsuario = 2131165189;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BuscarLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LoginLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RegistrarServiciolayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int RegistroServiciosLocal = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ServicesDetailLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ServicesLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ServicioLocalView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int toolbar2 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int toolBarLayout = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int home = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int photo_edit = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int codMovil = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Layouts = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int MyCustomTheme = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int button_text = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
