//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sas_Futura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sas_Motivos
    {
        public string IdEmpresa { get; set; }
        public string IdMotivo { get; set; }
        public string Motivo { get; set; }
        public string IdProducto { get; set; }
        public string sas_Preguntas_Clave { get; set; }
        public string sas_Instrucciones { get; set; }
        public string sas_Respuestas1 { get; set; }
        public string sas_Respuestas2 { get; set; }
        public string sas_Respuestas3 { get; set; }
        public string sas_Causas { get; set; }
        public string sas_Obs { get; set; }
        public Nullable<bool> Activo { get; set; }
    }
}
