//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sas_Futura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sas_Servicios
    {
        public int idSolicitud { get; set; }
        public Nullable<int> NroSolicitud { get; set; }
        public string idUsuario { get; set; }
        public Nullable<System.DateTime> fechaLlamada { get; set; }
        public string horaLlamada { get; set; }
        public string idTipoServicio { get; set; }
        public string OtroServicio { get; set; }
        public string Paciente { get; set; }
        public string Telefono { get; set; }
        public string idPaciente { get; set; }
        public Nullable<decimal> edad { get; set; }
        public string solicitante { get; set; }
        public string direccionRef { get; set; }
        public string direccionRef2 { get; set; }
        public string nrocasa { get; set; }
        public string referencia { get; set; }
        public string idSeguro { get; set; }
        public string NroSeguro { get; set; }
        public string idZona { get; set; }
        public string Motivo { get; set; }
        public Nullable<System.DateTime> fechaAgenda { get; set; }
        public string obs { get; set; }
        public string Comentario { get; set; }
        public Nullable<int> NroAutoriza { get; set; }
        public string CI { get; set; }
        public string Autoriza { get; set; }
        public string IdTipoSeguro { get; set; }
        public string IdSucursal { get; set; }
        public string nroSalida { get; set; }
        public string idMovil { get; set; }
        public string idtipoAtencion { get; set; }
        public Nullable<int> kmSalida { get; set; }
        public Nullable<int> kmLlegada { get; set; }
        public Nullable<int> kmSalida1 { get; set; }
        public Nullable<int> kmLlegada1 { get; set; }
        public Nullable<int> kmSalida2 { get; set; }
        public Nullable<int> kmLlegada2 { get; set; }
        public Nullable<int> kmSalida3 { get; set; }
        public Nullable<int> kmLlegada3 { get; set; }
        public Nullable<int> kmSalida4 { get; set; }
        public Nullable<int> KmLlegada4 { get; set; }
        public string horaSalida { get; set; }
        public string horaLlegada { get; set; }
        public string horaSalida1 { get; set; }
        public string horaLlegada1 { get; set; }
        public string horaSalida2 { get; set; }
        public string horaLlegada2 { get; set; }
        public string horaSalida3 { get; set; }
        public string horaLlegada3 { get; set; }
        public string horaSalida4 { get; set; }
        public string horaLlegada4 { get; set; }
        public string lugarInternacion { get; set; }
        public string chofer { get; set; }
        public string paramedico { get; set; }
        public string medico { get; set; }
        public string Acompañante { get; set; }
        public string incidencia1 { get; set; }
        public string incidencia2 { get; set; }
        public string incidencia3 { get; set; }
        public string NroFactura { get; set; }
        public Nullable<int> NroFS { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> cobrado { get; set; }
        public string observacion { get; set; }
        public string Estado { get; set; }
        public string idEmpresa { get; set; }
        public string IdTipoServicioFinal { get; set; }
        public string Destino { get; set; }
        public string TipoHora1 { get; set; }
        public string TipoHora2 { get; set; }
        public string TipoHora3 { get; set; }
        public string Receptor { get; set; }
        public string Despachante { get; set; }
        public Nullable<System.DateTime> Audit_Fecha { get; set; }
        public string Audit_Usuario { get; set; }
        public string sv_ta { get; set; }
        public string sv_fc { get; set; }
        public string sv_tempe { get; set; }
        public string sv_fresp { get; set; }
        public string hallazgo_exfisico { get; set; }
        public string tratAdministrado { get; set; }
        public string resp_tratam { get; set; }
        public string epicrisis { get; set; }
        public string dx_presuntivo { get; set; }
        public Nullable<int> NroHC { get; set; }
        public string NroContrato { get; set; }
        public string IdAfiliado { get; set; }
        public Nullable<int> IdRemision { get; set; }
        public string IdProducto { get; set; }
        public string IdProductoFinal { get; set; }
        public string HoraDespacho { get; set; }
        public Nullable<bool> Hipertenso { get; set; }
        public Nullable<bool> Cardiaco { get; set; }
        public Nullable<bool> Diabetico { get; set; }
        public Nullable<bool> Alergico { get; set; }
        public string AlergicoA { get; set; }
        public Nullable<bool> Asmatico { get; set; }
        public Nullable<bool> Tabaco { get; set; }
        public Nullable<bool> Epilepsia { get; set; }
        public string Otros { get; set; }
        public Nullable<bool> Acv { get; set; }
        public Nullable<bool> epoc { get; set; }
        public Nullable<System.DateTime> FechaAlerta { get; set; }
        public Nullable<bool> Alerta { get; set; }
        public string IdCliente { get; set; }
        public string IdVendedor { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public string HoraRecepcion { get; set; }
        public string HoraDisponible { get; set; }
        public string IdEstado { get; set; }
        public string HoraEstado { get; set; }
        public string IdDesenlace { get; set; }
        public string IdMotivo1 { get; set; }
        public string IdMotivo2 { get; set; }
        public string IdMotivo3 { get; set; }
        public string IdDiagnostico { get; set; }
        public string SAT { get; set; }
        public string Glasgow { get; set; }
        public string Glicemia { get; set; }
        public string IDComprobante { get; set; }
        public Nullable<decimal> numero { get; set; }
        public Nullable<decimal> ImporteFactura { get; set; }
        public string IdMotivoAnul { get; set; }
        public Nullable<int> NroEncuesta { get; set; }
    }
}
